// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers/auth_cli/auth_cli_handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/http/handlers/auth_cli/auth_cli_handlers.go -destination=internal/http/handlers/auth_cli/mocks/auth_service_mock.go -package=mocks -mock_names=AuthService=MockAuthService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	authservice "auth/internal/services/auth"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CliRefresh mocks base method.
func (m *MockAuthService) CliRefresh(ctx context.Context, input *authservice.CliRefreshInput) (*authservice.CliRefreshOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CliRefresh", ctx, input)
	ret0, _ := ret[0].(*authservice.CliRefreshOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CliRefresh indicates an expected call of CliRefresh.
func (mr *MockAuthServiceMockRecorder) CliRefresh(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CliRefresh", reflect.TypeOf((*MockAuthService)(nil).CliRefresh), ctx, input)
}

// DeviceConfirm mocks base method.
func (m *MockAuthService) DeviceConfirm(ctx context.Context, input *authservice.DeviceConfirmInput) (*authservice.DeviceConfirmOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceConfirm", ctx, input)
	ret0, _ := ret[0].(*authservice.DeviceConfirmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceConfirm indicates an expected call of DeviceConfirm.
func (mr *MockAuthServiceMockRecorder) DeviceConfirm(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceConfirm", reflect.TypeOf((*MockAuthService)(nil).DeviceConfirm), ctx, input)
}

// DeviceStart mocks base method.
func (m *MockAuthService) DeviceStart(ctx context.Context) (*authservice.DeviceStartOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceStart", ctx)
	ret0, _ := ret[0].(*authservice.DeviceStartOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceStart indicates an expected call of DeviceStart.
func (mr *MockAuthServiceMockRecorder) DeviceStart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceStart", reflect.TypeOf((*MockAuthService)(nil).DeviceStart), ctx)
}

// DeviceToken mocks base method.
func (m *MockAuthService) DeviceToken(ctx context.Context, input *authservice.DeviceTokenInput) (*authservice.DeviceTokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceToken", ctx, input)
	ret0, _ := ret[0].(*authservice.DeviceTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceToken indicates an expected call of DeviceToken.
func (mr *MockAuthServiceMockRecorder) DeviceToken(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceToken", reflect.TypeOf((*MockAuthService)(nil).DeviceToken), ctx, input)
}

// Refresh mocks base method.
func (m *MockAuthService) Refresh(ctx context.Context, input *authservice.RefreshInput) (*authservice.RefreshOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, input)
	ret0, _ := ret[0].(*authservice.RefreshOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthServiceMockRecorder) Refresh(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthService)(nil).Refresh), ctx, input)
}
