// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers/tasks_handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/http/handlers/tasks_handlers.go -destination=internal/http/handlers/mocks/handlers_mocks.go -package=mocks -mock_names=tasksService=MockTasksService,tagsService=MockTagsService,languagesService=MockLanguagesService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	services "tasks/internal/services"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTasksService is a mock of tasksService interface.
type MockTasksService struct {
	ctrl     *gomock.Controller
	recorder *MockTasksServiceMockRecorder
	isgomock struct{}
}

// MockTasksServiceMockRecorder is the mock recorder for MockTasksService.
type MockTasksServiceMockRecorder struct {
	mock *MockTasksService
}

// NewMockTasksService creates a new mock instance.
func NewMockTasksService(ctrl *gomock.Controller) *MockTasksService {
	mock := &MockTasksService{ctrl: ctrl}
	mock.recorder = &MockTasksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksService) EXPECT() *MockTasksServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTasksService) Create(ctx context.Context, input *services.CreateInput) (*services.TaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*services.TaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTasksServiceMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTasksService)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockTasksService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTasksServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTasksService)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTasksService) GetByID(ctx context.Context, id uuid.UUID) (*services.TaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*services.TaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTasksServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTasksService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTasksService) List(ctx context.Context, input *services.ListInput) (*services.ListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].(*services.ListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTasksServiceMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTasksService)(nil).List), ctx, input)
}

// Update mocks base method.
func (m *MockTasksService) Update(ctx context.Context, input *services.UpdateInput) (*services.TaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*services.TaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTasksServiceMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTasksService)(nil).Update), ctx, input)
}

// MockTagsService is a mock of tagsService interface.
type MockTagsService struct {
	ctrl     *gomock.Controller
	recorder *MockTagsServiceMockRecorder
	isgomock struct{}
}

// MockTagsServiceMockRecorder is the mock recorder for MockTagsService.
type MockTagsServiceMockRecorder struct {
	mock *MockTagsService
}

// NewMockTagsService creates a new mock instance.
func NewMockTagsService(ctrl *gomock.Controller) *MockTagsService {
	mock := &MockTagsService{ctrl: ctrl}
	mock.recorder = &MockTagsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagsService) EXPECT() *MockTagsServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTagsService) List(ctx context.Context) (*services.TagsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(*services.TagsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagsServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTagsService)(nil).List), ctx)
}

// MockLanguagesService is a mock of languagesService interface.
type MockLanguagesService struct {
	ctrl     *gomock.Controller
	recorder *MockLanguagesServiceMockRecorder
	isgomock struct{}
}

// MockLanguagesServiceMockRecorder is the mock recorder for MockLanguagesService.
type MockLanguagesServiceMockRecorder struct {
	mock *MockLanguagesService
}

// NewMockLanguagesService creates a new mock instance.
func NewMockLanguagesService(ctrl *gomock.Controller) *MockLanguagesService {
	mock := &MockLanguagesService{ctrl: ctrl}
	mock.recorder = &MockLanguagesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguagesService) EXPECT() *MockLanguagesServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockLanguagesService) List(ctx context.Context) (*services.LanguagesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(*services.LanguagesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLanguagesServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLanguagesService)(nil).List), ctx)
}
