// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/auth/auth.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/auth/auth.go -destination=internal/services/auth/mocks/auth_mocks.go -package=mocks -mock_names=tokenManager=MockTokenManager,rateLimiter=MockRateLimiter,eventProducer=MockEventProducer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	events "auth/internal/events"
	records "auth/internal/models/records"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenManager is a mock of tokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
	isgomock struct{}
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockTokenManager) GenerateAccessToken(userID, sessionID uuid.UUID) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenManagerMockRecorder) GenerateAccessToken(userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenManager)(nil).GenerateAccessToken), userID, sessionID)
}

// GenerateRefreshToken mocks base method.
func (m *MockTokenManager) GenerateRefreshToken() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockTokenManagerMockRecorder) GenerateRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockTokenManager)(nil).GenerateRefreshToken))
}

// ValidateAccessToken mocks base method.
func (m *MockTokenManager) ValidateAccessToken(tokenString string) (uuid.UUID, uuid.UUID, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenString)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenManagerMockRecorder) ValidateAccessToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenManager)(nil).ValidateAccessToken), tokenString)
}

// MockIdentityRepository is a mock of IdentityRepository interface.
type MockIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityRepositoryMockRecorder is the mock recorder for MockIdentityRepository.
type MockIdentityRepositoryMockRecorder struct {
	mock *MockIdentityRepository
}

// NewMockIdentityRepository creates a new mock instance.
func NewMockIdentityRepository(ctrl *gomock.Controller) *MockIdentityRepository {
	mock := &MockIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRepository) EXPECT() *MockIdentityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityRepository) Create(ctx context.Context, identity *records.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIdentityRepositoryMockRecorder) Create(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityRepository)(nil).Create), ctx, identity)
}

// GetByEmail mocks base method.
func (m *MockIdentityRepository) GetByEmail(ctx context.Context, email string) (*records.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*records.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockIdentityRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockIdentityRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockIdentityRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityRepository)(nil).GetByID), ctx, id)
}

// SetEmailVerified mocks base method.
func (m *MockIdentityRepository) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmailVerified", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmailVerified indicates an expected call of SetEmailVerified.
func (mr *MockIdentityRepositoryMockRecorder) SetEmailVerified(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmailVerified", reflect.TypeOf((*MockIdentityRepository)(nil).SetEmailVerified), ctx, id)
}

// SetStatus mocks base method.
func (m *MockIdentityRepository) SetStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockIdentityRepositoryMockRecorder) SetStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockIdentityRepository)(nil).SetStatus), ctx, id, status)
}

// SoftDelete mocks base method.
func (m *MockIdentityRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockIdentityRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockIdentityRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockIdentityRepository) Update(ctx context.Context, identity *records.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIdentityRepositoryMockRecorder) Update(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityRepository)(nil).Update), ctx, identity)
}

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCredentialRepository) Create(ctx context.Context, credential *records.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCredentialRepositoryMockRecorder) Create(ctx, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCredentialRepository)(nil).Create), ctx, credential)
}

// GetByIdentityID mocks base method.
func (m *MockCredentialRepository) GetByIdentityID(ctx context.Context, identityID uuid.UUID) (*records.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdentityID", ctx, identityID)
	ret0, _ := ret[0].(*records.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdentityID indicates an expected call of GetByIdentityID.
func (mr *MockCredentialRepositoryMockRecorder) GetByIdentityID(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdentityID", reflect.TypeOf((*MockCredentialRepository)(nil).GetByIdentityID), ctx, identityID)
}

// UpdatePassword mocks base method.
func (m *MockCredentialRepository) UpdatePassword(ctx context.Context, identityID uuid.UUID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, identityID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockCredentialRepositoryMockRecorder) UpdatePassword(ctx, identityID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockCredentialRepository)(nil).UpdatePassword), ctx, identityID, passwordHash)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, session *records.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, session)
}

// DeleteExpired mocks base method.
func (m *MockSessionRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockSessionRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockSessionRepository)(nil).DeleteExpired), ctx)
}

// GetActiveByIdentityID mocks base method.
func (m *MockSessionRepository) GetActiveByIdentityID(ctx context.Context, identityID uuid.UUID) ([]*records.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByIdentityID", ctx, identityID)
	ret0, _ := ret[0].([]*records.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByIdentityID indicates an expected call of GetActiveByIdentityID.
func (mr *MockSessionRepositoryMockRecorder) GetActiveByIdentityID(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByIdentityID", reflect.TypeOf((*MockSessionRepository)(nil).GetActiveByIdentityID), ctx, identityID)
}

// GetByID mocks base method.
func (m *MockSessionRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSessionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSessionRepository)(nil).GetByID), ctx, id)
}

// GetByRefreshTokenHash mocks base method.
func (m *MockSessionRepository) GetByRefreshTokenHash(ctx context.Context, hash string) (*records.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRefreshTokenHash", ctx, hash)
	ret0, _ := ret[0].(*records.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRefreshTokenHash indicates an expected call of GetByRefreshTokenHash.
func (mr *MockSessionRepositoryMockRecorder) GetByRefreshTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRefreshTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).GetByRefreshTokenHash), ctx, hash)
}

// Revoke mocks base method.
func (m *MockSessionRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSessionRepositoryMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSessionRepository)(nil).Revoke), ctx, id)
}

// RevokeAllByIdentityID mocks base method.
func (m *MockSessionRepository) RevokeAllByIdentityID(ctx context.Context, identityID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByIdentityID", ctx, identityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllByIdentityID indicates an expected call of RevokeAllByIdentityID.
func (mr *MockSessionRepositoryMockRecorder) RevokeAllByIdentityID(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByIdentityID", reflect.TypeOf((*MockSessionRepository)(nil).RevokeAllByIdentityID), ctx, identityID)
}

// MockVerificationCodeRepository is a mock of VerificationCodeRepository interface.
type MockVerificationCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationCodeRepositoryMockRecorder is the mock recorder for MockVerificationCodeRepository.
type MockVerificationCodeRepositoryMockRecorder struct {
	mock *MockVerificationCodeRepository
}

// NewMockVerificationCodeRepository creates a new mock instance.
func NewMockVerificationCodeRepository(ctrl *gomock.Controller) *MockVerificationCodeRepository {
	mock := &MockVerificationCodeRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationCodeRepository) EXPECT() *MockVerificationCodeRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockVerificationCodeRepository) Consume(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockVerificationCodeRepositoryMockRecorder) Consume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockVerificationCodeRepository)(nil).Consume), ctx, id)
}

// Create mocks base method.
func (m *MockVerificationCodeRepository) Create(ctx context.Context, code *records.VerificationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationCodeRepositoryMockRecorder) Create(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationCodeRepository)(nil).Create), ctx, code)
}

// DeleteExpired mocks base method.
func (m *MockVerificationCodeRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockVerificationCodeRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockVerificationCodeRepository)(nil).DeleteExpired), ctx)
}

// GetActiveByEmailAndPurpose mocks base method.
func (m *MockVerificationCodeRepository) GetActiveByEmailAndPurpose(ctx context.Context, email, purpose string) (*records.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByEmailAndPurpose", ctx, email, purpose)
	ret0, _ := ret[0].(*records.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByEmailAndPurpose indicates an expected call of GetActiveByEmailAndPurpose.
func (mr *MockVerificationCodeRepositoryMockRecorder) GetActiveByEmailAndPurpose(ctx, email, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByEmailAndPurpose", reflect.TypeOf((*MockVerificationCodeRepository)(nil).GetActiveByEmailAndPurpose), ctx, email, purpose)
}

// GetActiveByIdentityIDAndPurpose mocks base method.
func (m *MockVerificationCodeRepository) GetActiveByIdentityIDAndPurpose(ctx context.Context, identityID uuid.UUID, purpose string) (*records.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByIdentityIDAndPurpose", ctx, identityID, purpose)
	ret0, _ := ret[0].(*records.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByIdentityIDAndPurpose indicates an expected call of GetActiveByIdentityIDAndPurpose.
func (mr *MockVerificationCodeRepositoryMockRecorder) GetActiveByIdentityIDAndPurpose(ctx, identityID, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByIdentityIDAndPurpose", reflect.TypeOf((*MockVerificationCodeRepository)(nil).GetActiveByIdentityIDAndPurpose), ctx, identityID, purpose)
}

// GetByID mocks base method.
func (m *MockVerificationCodeRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVerificationCodeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVerificationCodeRepository)(nil).GetByID), ctx, id)
}

// IncrementAttempts mocks base method.
func (m *MockVerificationCodeRepository) IncrementAttempts(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAttempts", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAttempts indicates an expected call of IncrementAttempts.
func (mr *MockVerificationCodeRepositoryMockRecorder) IncrementAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAttempts", reflect.TypeOf((*MockVerificationCodeRepository)(nil).IncrementAttempts), ctx, id)
}

// MockPasswordResetTokenRepository is a mock of PasswordResetTokenRepository interface.
type MockPasswordResetTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordResetTokenRepositoryMockRecorder is the mock recorder for MockPasswordResetTokenRepository.
type MockPasswordResetTokenRepositoryMockRecorder struct {
	mock *MockPasswordResetTokenRepository
}

// NewMockPasswordResetTokenRepository creates a new mock instance.
func NewMockPasswordResetTokenRepository(ctrl *gomock.Controller) *MockPasswordResetTokenRepository {
	mock := &MockPasswordResetTokenRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetTokenRepository) EXPECT() *MockPasswordResetTokenRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockPasswordResetTokenRepository) Consume(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) Consume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).Consume), ctx, id)
}

// Create mocks base method.
func (m *MockPasswordResetTokenRepository) Create(ctx context.Context, token *records.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).Create), ctx, token)
}

// DeleteExpired mocks base method.
func (m *MockPasswordResetTokenRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).DeleteExpired), ctx)
}

// GetByID mocks base method.
func (m *MockPasswordResetTokenRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).GetByID), ctx, id)
}

// GetByTokenHash mocks base method.
func (m *MockPasswordResetTokenRepository) GetByTokenHash(ctx context.Context, hash string) (*records.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, hash)
	ret0, _ := ret[0].(*records.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) GetByTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).GetByTokenHash), ctx, hash)
}

// MockPasswordChangeTokenRepository is a mock of PasswordChangeTokenRepository interface.
type MockPasswordChangeTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordChangeTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordChangeTokenRepositoryMockRecorder is the mock recorder for MockPasswordChangeTokenRepository.
type MockPasswordChangeTokenRepositoryMockRecorder struct {
	mock *MockPasswordChangeTokenRepository
}

// NewMockPasswordChangeTokenRepository creates a new mock instance.
func NewMockPasswordChangeTokenRepository(ctrl *gomock.Controller) *MockPasswordChangeTokenRepository {
	mock := &MockPasswordChangeTokenRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordChangeTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordChangeTokenRepository) EXPECT() *MockPasswordChangeTokenRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockPasswordChangeTokenRepository) Consume(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockPasswordChangeTokenRepositoryMockRecorder) Consume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockPasswordChangeTokenRepository)(nil).Consume), ctx, id)
}

// Create mocks base method.
func (m *MockPasswordChangeTokenRepository) Create(ctx context.Context, token *records.PasswordChangeToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordChangeTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordChangeTokenRepository)(nil).Create), ctx, token)
}

// DeleteExpired mocks base method.
func (m *MockPasswordChangeTokenRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockPasswordChangeTokenRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockPasswordChangeTokenRepository)(nil).DeleteExpired), ctx)
}

// GetByTokenHash mocks base method.
func (m *MockPasswordChangeTokenRepository) GetByTokenHash(ctx context.Context, hash string) (*records.PasswordChangeToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, hash)
	ret0, _ := ret[0].(*records.PasswordChangeToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockPasswordChangeTokenRepositoryMockRecorder) GetByTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockPasswordChangeTokenRepository)(nil).GetByTokenHash), ctx, hash)
}

// MockEmailChangeRequestRepository is a mock of EmailChangeRequestRepository interface.
type MockEmailChangeRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailChangeRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailChangeRequestRepositoryMockRecorder is the mock recorder for MockEmailChangeRequestRepository.
type MockEmailChangeRequestRepositoryMockRecorder struct {
	mock *MockEmailChangeRequestRepository
}

// NewMockEmailChangeRequestRepository creates a new mock instance.
func NewMockEmailChangeRequestRepository(ctrl *gomock.Controller) *MockEmailChangeRequestRepository {
	mock := &MockEmailChangeRequestRepository{ctrl: ctrl}
	mock.recorder = &MockEmailChangeRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailChangeRequestRepository) EXPECT() *MockEmailChangeRequestRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockEmailChangeRequestRepository) Consume(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) Consume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).Consume), ctx, id)
}

// Create mocks base method.
func (m *MockEmailChangeRequestRepository) Create(ctx context.Context, req *records.EmailChangeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).Create), ctx, req)
}

// GetActiveByIdentityIDAndStatus mocks base method.
func (m *MockEmailChangeRequestRepository) GetActiveByIdentityIDAndStatus(ctx context.Context, identityID uuid.UUID, status string) (*records.EmailChangeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByIdentityIDAndStatus", ctx, identityID, status)
	ret0, _ := ret[0].(*records.EmailChangeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByIdentityIDAndStatus indicates an expected call of GetActiveByIdentityIDAndStatus.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) GetActiveByIdentityIDAndStatus(ctx, identityID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByIdentityIDAndStatus", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).GetActiveByIdentityIDAndStatus), ctx, identityID, status)
}

// GetByID mocks base method.
func (m *MockEmailChangeRequestRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.EmailChangeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.EmailChangeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).GetByID), ctx, id)
}

// GetByTokenHash mocks base method.
func (m *MockEmailChangeRequestRepository) GetByTokenHash(ctx context.Context, hash string) (*records.EmailChangeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, hash)
	ret0, _ := ret[0].(*records.EmailChangeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) GetByTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).GetByTokenHash), ctx, hash)
}

// SetStatus mocks base method.
func (m *MockEmailChangeRequestRepository) SetStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) SetStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).SetStatus), ctx, id, status)
}

// UpdateNewEmailAndStatus mocks base method.
func (m *MockEmailChangeRequestRepository) UpdateNewEmailAndStatus(ctx context.Context, id uuid.UUID, newEmail, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNewEmailAndStatus", ctx, id, newEmail, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNewEmailAndStatus indicates an expected call of UpdateNewEmailAndStatus.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) UpdateNewEmailAndStatus(ctx, id, newEmail, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNewEmailAndStatus", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).UpdateNewEmailAndStatus), ctx, id, newEmail, status)
}

// UpdateTokenHash mocks base method.
func (m *MockEmailChangeRequestRepository) UpdateTokenHash(ctx context.Context, id uuid.UUID, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenHash", ctx, id, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenHash indicates an expected call of UpdateTokenHash.
func (mr *MockEmailChangeRequestRepositoryMockRecorder) UpdateTokenHash(ctx, id, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenHash", reflect.TypeOf((*MockEmailChangeRequestRepository)(nil).UpdateTokenHash), ctx, id, tokenHash)
}

// MockAccountDeleteRequestRepository is a mock of AccountDeleteRequestRepository interface.
type MockAccountDeleteRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountDeleteRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountDeleteRequestRepositoryMockRecorder is the mock recorder for MockAccountDeleteRequestRepository.
type MockAccountDeleteRequestRepositoryMockRecorder struct {
	mock *MockAccountDeleteRequestRepository
}

// NewMockAccountDeleteRequestRepository creates a new mock instance.
func NewMockAccountDeleteRequestRepository(ctrl *gomock.Controller) *MockAccountDeleteRequestRepository {
	mock := &MockAccountDeleteRequestRepository{ctrl: ctrl}
	mock.recorder = &MockAccountDeleteRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountDeleteRequestRepository) EXPECT() *MockAccountDeleteRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountDeleteRequestRepository) Create(ctx context.Context, req *records.AccountDeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountDeleteRequestRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountDeleteRequestRepository)(nil).Create), ctx, req)
}

// GetActiveByIdentityID mocks base method.
func (m *MockAccountDeleteRequestRepository) GetActiveByIdentityID(ctx context.Context, identityID uuid.UUID) (*records.AccountDeleteRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByIdentityID", ctx, identityID)
	ret0, _ := ret[0].(*records.AccountDeleteRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByIdentityID indicates an expected call of GetActiveByIdentityID.
func (mr *MockAccountDeleteRequestRepositoryMockRecorder) GetActiveByIdentityID(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByIdentityID", reflect.TypeOf((*MockAccountDeleteRequestRepository)(nil).GetActiveByIdentityID), ctx, identityID)
}

// GetByID mocks base method.
func (m *MockAccountDeleteRequestRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.AccountDeleteRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.AccountDeleteRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountDeleteRequestRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountDeleteRequestRepository)(nil).GetByID), ctx, id)
}

// SetStatus mocks base method.
func (m *MockAccountDeleteRequestRepository) SetStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockAccountDeleteRequestRepositoryMockRecorder) SetStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockAccountDeleteRequestRepository)(nil).SetStatus), ctx, id, status)
}

// MockAuthEventRepository is a mock of AuthEventRepository interface.
type MockAuthEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthEventRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthEventRepositoryMockRecorder is the mock recorder for MockAuthEventRepository.
type MockAuthEventRepositoryMockRecorder struct {
	mock *MockAuthEventRepository
}

// NewMockAuthEventRepository creates a new mock instance.
func NewMockAuthEventRepository(ctrl *gomock.Controller) *MockAuthEventRepository {
	mock := &MockAuthEventRepository{ctrl: ctrl}
	mock.recorder = &MockAuthEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthEventRepository) EXPECT() *MockAuthEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthEventRepository) Create(ctx context.Context, event *records.AuthEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthEventRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthEventRepository)(nil).Create), ctx, event)
}

// GetByEventType mocks base method.
func (m *MockAuthEventRepository) GetByEventType(ctx context.Context, eventType string) ([]*records.AuthEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventType", ctx, eventType)
	ret0, _ := ret[0].([]*records.AuthEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventType indicates an expected call of GetByEventType.
func (mr *MockAuthEventRepositoryMockRecorder) GetByEventType(ctx, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventType", reflect.TypeOf((*MockAuthEventRepository)(nil).GetByEventType), ctx, eventType)
}

// GetByID mocks base method.
func (m *MockAuthEventRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.AuthEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.AuthEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuthEventRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuthEventRepository)(nil).GetByID), ctx, id)
}

// GetByIdentityID mocks base method.
func (m *MockAuthEventRepository) GetByIdentityID(ctx context.Context, identityID uuid.UUID) ([]*records.AuthEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdentityID", ctx, identityID)
	ret0, _ := ret[0].([]*records.AuthEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdentityID indicates an expected call of GetByIdentityID.
func (mr *MockAuthEventRepositoryMockRecorder) GetByIdentityID(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdentityID", reflect.TypeOf((*MockAuthEventRepository)(nil).GetByIdentityID), ctx, identityID)
}

// MockDeviceAuthorizationRepository is a mock of DeviceAuthorizationRepository interface.
type MockDeviceAuthorizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceAuthorizationRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceAuthorizationRepositoryMockRecorder is the mock recorder for MockDeviceAuthorizationRepository.
type MockDeviceAuthorizationRepositoryMockRecorder struct {
	mock *MockDeviceAuthorizationRepository
}

// NewMockDeviceAuthorizationRepository creates a new mock instance.
func NewMockDeviceAuthorizationRepository(ctrl *gomock.Controller) *MockDeviceAuthorizationRepository {
	mock := &MockDeviceAuthorizationRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceAuthorizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceAuthorizationRepository) EXPECT() *MockDeviceAuthorizationRepositoryMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockDeviceAuthorizationRepository) Confirm(ctx context.Context, id, identityID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, id, identityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) Confirm(ctx, id, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).Confirm), ctx, id, identityID)
}

// Create mocks base method.
func (m *MockDeviceAuthorizationRepository) Create(ctx context.Context, dac *records.DeviceAuthorizationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dac)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) Create(ctx, dac any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).Create), ctx, dac)
}

// DeleteExpired mocks base method.
func (m *MockDeviceAuthorizationRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).DeleteExpired), ctx)
}

// GetByDeviceCodeHash mocks base method.
func (m *MockDeviceAuthorizationRepository) GetByDeviceCodeHash(ctx context.Context, deviceCodeHash string) (*records.DeviceAuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDeviceCodeHash", ctx, deviceCodeHash)
	ret0, _ := ret[0].(*records.DeviceAuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDeviceCodeHash indicates an expected call of GetByDeviceCodeHash.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) GetByDeviceCodeHash(ctx, deviceCodeHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDeviceCodeHash", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).GetByDeviceCodeHash), ctx, deviceCodeHash)
}

// GetByUserCode mocks base method.
func (m *MockDeviceAuthorizationRepository) GetByUserCode(ctx context.Context, userCode string) (*records.DeviceAuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserCode", ctx, userCode)
	ret0, _ := ret[0].(*records.DeviceAuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserCode indicates an expected call of GetByUserCode.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) GetByUserCode(ctx, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserCode", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).GetByUserCode), ctx, userCode)
}

// UpdateLastPolledAt mocks base method.
func (m *MockDeviceAuthorizationRepository) UpdateLastPolledAt(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastPolledAt", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastPolledAt indicates an expected call of UpdateLastPolledAt.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) UpdateLastPolledAt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastPolledAt", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).UpdateLastPolledAt), ctx, id)
}

// MockRateLimiter is a mock of rateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiter) Allow(ctx context.Context, key string, cooldown, window time.Duration, maxRequests int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, key, cooldown, window, maxRequests)
	ret0, _ := ret[0].(error)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterMockRecorder) Allow(ctx, key, cooldown, window, maxRequests any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiter)(nil).Allow), ctx, key, cooldown, window, maxRequests)
}

// MockEventProducer is a mock of eventProducer interface.
type MockEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockEventProducerMockRecorder
	isgomock struct{}
}

// MockEventProducerMockRecorder is the mock recorder for MockEventProducer.
type MockEventProducerMockRecorder struct {
	mock *MockEventProducer
}

// NewMockEventProducer creates a new mock instance.
func NewMockEventProducer(ctrl *gomock.Controller) *MockEventProducer {
	mock := &MockEventProducer{ctrl: ctrl}
	mock.recorder = &MockEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProducer) EXPECT() *MockEventProducerMockRecorder {
	return m.recorder
}

// PublishAccountDeleteCodeSend mocks base method.
func (m *MockEventProducer) PublishAccountDeleteCodeSend(ctx context.Context, payload events.VerificationCodeSendPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAccountDeleteCodeSend", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAccountDeleteCodeSend indicates an expected call of PublishAccountDeleteCodeSend.
func (mr *MockEventProducerMockRecorder) PublishAccountDeleteCodeSend(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAccountDeleteCodeSend", reflect.TypeOf((*MockEventProducer)(nil).PublishAccountDeleteCodeSend), ctx, payload)
}

// PublishEmailChangeCodeSend mocks base method.
func (m *MockEventProducer) PublishEmailChangeCodeSend(ctx context.Context, payload events.VerificationCodeSendPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEmailChangeCodeSend", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEmailChangeCodeSend indicates an expected call of PublishEmailChangeCodeSend.
func (mr *MockEventProducerMockRecorder) PublishEmailChangeCodeSend(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEmailChangeCodeSend", reflect.TypeOf((*MockEventProducer)(nil).PublishEmailChangeCodeSend), ctx, payload)
}

// PublishIdentityCreated mocks base method.
func (m *MockEventProducer) PublishIdentityCreated(ctx context.Context, payload events.IdentityCreatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishIdentityCreated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishIdentityCreated indicates an expected call of PublishIdentityCreated.
func (mr *MockEventProducerMockRecorder) PublishIdentityCreated(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishIdentityCreated", reflect.TypeOf((*MockEventProducer)(nil).PublishIdentityCreated), ctx, payload)
}

// PublishIdentityDeleted mocks base method.
func (m *MockEventProducer) PublishIdentityDeleted(ctx context.Context, payload events.IdentityDeletedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishIdentityDeleted", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishIdentityDeleted indicates an expected call of PublishIdentityDeleted.
func (mr *MockEventProducerMockRecorder) PublishIdentityDeleted(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishIdentityDeleted", reflect.TypeOf((*MockEventProducer)(nil).PublishIdentityDeleted), ctx, payload)
}

// PublishIdentityLogin mocks base method.
func (m *MockEventProducer) PublishIdentityLogin(ctx context.Context, payload events.IdentityLoginPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishIdentityLogin", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishIdentityLogin indicates an expected call of PublishIdentityLogin.
func (mr *MockEventProducerMockRecorder) PublishIdentityLogin(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishIdentityLogin", reflect.TypeOf((*MockEventProducer)(nil).PublishIdentityLogin), ctx, payload)
}

// PublishIdentityLogout mocks base method.
func (m *MockEventProducer) PublishIdentityLogout(ctx context.Context, payload events.IdentityLogoutPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishIdentityLogout", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishIdentityLogout indicates an expected call of PublishIdentityLogout.
func (mr *MockEventProducerMockRecorder) PublishIdentityLogout(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishIdentityLogout", reflect.TypeOf((*MockEventProducer)(nil).PublishIdentityLogout), ctx, payload)
}

// PublishIdentityUpdated mocks base method.
func (m *MockEventProducer) PublishIdentityUpdated(ctx context.Context, payload events.IdentityUpdatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishIdentityUpdated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishIdentityUpdated indicates an expected call of PublishIdentityUpdated.
func (mr *MockEventProducerMockRecorder) PublishIdentityUpdated(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishIdentityUpdated", reflect.TypeOf((*MockEventProducer)(nil).PublishIdentityUpdated), ctx, payload)
}

// PublishPasswordChangeCodeSend mocks base method.
func (m *MockEventProducer) PublishPasswordChangeCodeSend(ctx context.Context, payload events.VerificationCodeSendPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPasswordChangeCodeSend", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPasswordChangeCodeSend indicates an expected call of PublishPasswordChangeCodeSend.
func (mr *MockEventProducerMockRecorder) PublishPasswordChangeCodeSend(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPasswordChangeCodeSend", reflect.TypeOf((*MockEventProducer)(nil).PublishPasswordChangeCodeSend), ctx, payload)
}

// PublishPasswordResetCodeSend mocks base method.
func (m *MockEventProducer) PublishPasswordResetCodeSend(ctx context.Context, payload events.VerificationCodeSendPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPasswordResetCodeSend", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPasswordResetCodeSend indicates an expected call of PublishPasswordResetCodeSend.
func (mr *MockEventProducerMockRecorder) PublishPasswordResetCodeSend(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPasswordResetCodeSend", reflect.TypeOf((*MockEventProducer)(nil).PublishPasswordResetCodeSend), ctx, payload)
}

// PublishVerificationCodeSend mocks base method.
func (m *MockEventProducer) PublishVerificationCodeSend(ctx context.Context, payload events.VerificationCodeSendPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishVerificationCodeSend", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishVerificationCodeSend indicates an expected call of PublishVerificationCodeSend.
func (mr *MockEventProducerMockRecorder) PublishVerificationCodeSend(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishVerificationCodeSend", reflect.TypeOf((*MockEventProducer)(nil).PublishVerificationCodeSend), ctx, payload)
}
