// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers/users_handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/http/handlers/users_handlers.go -destination=internal/http/handlers/mocks/handlers_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	service "users/internal/services"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockusersService is a mock of usersService interface.
type MockusersService struct {
	ctrl     *gomock.Controller
	recorder *MockusersServiceMockRecorder
	isgomock struct{}
}

// MockusersServiceMockRecorder is the mock recorder for MockusersService.
type MockusersServiceMockRecorder struct {
	mock *MockusersService
}

// NewMockusersService creates a new mock instance.
func NewMockusersService(ctrl *gomock.Controller) *MockusersService {
	mock := &MockusersService{ctrl: ctrl}
	mock.recorder = &MockusersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersService) EXPECT() *MockusersServiceMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockusersService) DeleteAvatar(ctx context.Context) (*service.DeleteAvatarOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx)
	ret0, _ := ret[0].(*service.DeleteAvatarOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockusersServiceMockRecorder) DeleteAvatar(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockusersService)(nil).DeleteAvatar), ctx)
}

// GetGitMe mocks base method.
func (m *MockusersService) GetGitMe(ctx context.Context, identityID uuid.UUID) (*service.GitMeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitMe", ctx, identityID)
	ret0, _ := ret[0].(*service.GitMeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitMe indicates an expected call of GetGitMe.
func (mr *MockusersServiceMockRecorder) GetGitMe(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitMe", reflect.TypeOf((*MockusersService)(nil).GetGitMe), ctx, identityID)
}

// GetProfile mocks base method.
func (m *MockusersService) GetProfile(ctx context.Context) (*service.ProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx)
	ret0, _ := ret[0].(*service.ProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockusersServiceMockRecorder) GetProfile(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockusersService)(nil).GetProfile), ctx)
}

// UpdateAvatar mocks base method.
func (m *MockusersService) UpdateAvatar(ctx context.Context, input *service.UpdateAvatarInput) (*service.UpdateAvatarOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, input)
	ret0, _ := ret[0].(*service.UpdateAvatarOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockusersServiceMockRecorder) UpdateAvatar(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockusersService)(nil).UpdateAvatar), ctx, input)
}

// UpdateSettings mocks base method.
func (m *MockusersService) UpdateSettings(ctx context.Context, input *service.UpdateSettingsInput) (*service.ProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, input)
	ret0, _ := ret[0].(*service.ProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockusersServiceMockRecorder) UpdateSettings(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockusersService)(nil).UpdateSettings), ctx, input)
}
