// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers/auth_handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/http/handlers/auth_handlers.go -destination=internal/http/handlers/mocks/auth_service_mock.go -package=mocks -mock_names=authService=MockAuthService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	authservice "auth/internal/services/auth"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of authService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// ChangeEmail mocks base method.
func (m *MockAuthService) ChangeEmail(ctx context.Context, input *authservice.ChangeEmailInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmail", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmail indicates an expected call of ChangeEmail.
func (mr *MockAuthServiceMockRecorder) ChangeEmail(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmail", reflect.TypeOf((*MockAuthService)(nil).ChangeEmail), ctx, input)
}

// ChangeEmailCodeResend mocks base method.
func (m *MockAuthService) ChangeEmailCodeResend(ctx context.Context, input *authservice.ChangeEmailResendInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmailCodeResend", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmailCodeResend indicates an expected call of ChangeEmailCodeResend.
func (mr *MockAuthServiceMockRecorder) ChangeEmailCodeResend(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmailCodeResend", reflect.TypeOf((*MockAuthService)(nil).ChangeEmailCodeResend), ctx, input)
}

// ChangeEmailComplete mocks base method.
func (m *MockAuthService) ChangeEmailComplete(ctx context.Context, input *authservice.ChangeEmailCompleteInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmailComplete", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmailComplete indicates an expected call of ChangeEmailComplete.
func (mr *MockAuthServiceMockRecorder) ChangeEmailComplete(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmailComplete", reflect.TypeOf((*MockAuthService)(nil).ChangeEmailComplete), ctx, input)
}

// ChangeEmailConfirm mocks base method.
func (m *MockAuthService) ChangeEmailConfirm(ctx context.Context, input *authservice.ChangeEmailConfirmInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmailConfirm", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmailConfirm indicates an expected call of ChangeEmailConfirm.
func (mr *MockAuthServiceMockRecorder) ChangeEmailConfirm(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmailConfirm", reflect.TypeOf((*MockAuthService)(nil).ChangeEmailConfirm), ctx, input)
}

// ChangeEmailVerify mocks base method.
func (m *MockAuthService) ChangeEmailVerify(ctx context.Context, input *authservice.ChangeEmailVerifyInput) (*authservice.ChangeEmailVerifyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmailVerify", ctx, input)
	ret0, _ := ret[0].(*authservice.ChangeEmailVerifyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmailVerify indicates an expected call of ChangeEmailVerify.
func (mr *MockAuthServiceMockRecorder) ChangeEmailVerify(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmailVerify", reflect.TypeOf((*MockAuthService)(nil).ChangeEmailVerify), ctx, input)
}

// ChangePassword mocks base method.
func (m *MockAuthService) ChangePassword(ctx context.Context, input *authservice.ChangePasswordInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthServiceMockRecorder) ChangePassword(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthService)(nil).ChangePassword), ctx, input)
}

// ChangePasswordCodeResend mocks base method.
func (m *MockAuthService) ChangePasswordCodeResend(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePasswordCodeResend", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePasswordCodeResend indicates an expected call of ChangePasswordCodeResend.
func (mr *MockAuthServiceMockRecorder) ChangePasswordCodeResend(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePasswordCodeResend", reflect.TypeOf((*MockAuthService)(nil).ChangePasswordCodeResend), ctx)
}

// ChangePasswordVerify mocks base method.
func (m *MockAuthService) ChangePasswordVerify(ctx context.Context, input *authservice.ChangePasswordVerifyInput) (*authservice.ChangePasswordVerifyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePasswordVerify", ctx, input)
	ret0, _ := ret[0].(*authservice.ChangePasswordVerifyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePasswordVerify indicates an expected call of ChangePasswordVerify.
func (mr *MockAuthServiceMockRecorder) ChangePasswordVerify(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePasswordVerify", reflect.TypeOf((*MockAuthService)(nil).ChangePasswordVerify), ctx, input)
}

// CliRefresh mocks base method.
func (m *MockAuthService) CliRefresh(ctx context.Context, input *authservice.CliRefreshInput) (*authservice.CliRefreshOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CliRefresh", ctx, input)
	ret0, _ := ret[0].(*authservice.CliRefreshOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CliRefresh indicates an expected call of CliRefresh.
func (mr *MockAuthServiceMockRecorder) CliRefresh(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CliRefresh", reflect.TypeOf((*MockAuthService)(nil).CliRefresh), ctx, input)
}

// CompletePasswordChange mocks base method.
func (m *MockAuthService) CompletePasswordChange(ctx context.Context, input *authservice.CompletePasswordChangeInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompletePasswordChange", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompletePasswordChange indicates an expected call of CompletePasswordChange.
func (mr *MockAuthServiceMockRecorder) CompletePasswordChange(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompletePasswordChange", reflect.TypeOf((*MockAuthService)(nil).CompletePasswordChange), ctx, input)
}

// DeleteAccount mocks base method.
func (m *MockAuthService) DeleteAccount(ctx context.Context, input *authservice.DeleteAccountInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockAuthServiceMockRecorder) DeleteAccount(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockAuthService)(nil).DeleteAccount), ctx, input)
}

// DeleteAccountCodeResend mocks base method.
func (m *MockAuthService) DeleteAccountCodeResend(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountCodeResend", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccountCodeResend indicates an expected call of DeleteAccountCodeResend.
func (mr *MockAuthServiceMockRecorder) DeleteAccountCodeResend(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountCodeResend", reflect.TypeOf((*MockAuthService)(nil).DeleteAccountCodeResend), ctx)
}

// DeleteAccountVerify mocks base method.
func (m *MockAuthService) DeleteAccountVerify(ctx context.Context, input *authservice.DeleteAccountVerifyInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountVerify", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccountVerify indicates an expected call of DeleteAccountVerify.
func (mr *MockAuthServiceMockRecorder) DeleteAccountVerify(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountVerify", reflect.TypeOf((*MockAuthService)(nil).DeleteAccountVerify), ctx, input)
}

// DeviceConfirm mocks base method.
func (m *MockAuthService) DeviceConfirm(ctx context.Context, input *authservice.DeviceConfirmInput) (*authservice.DeviceConfirmOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceConfirm", ctx, input)
	ret0, _ := ret[0].(*authservice.DeviceConfirmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceConfirm indicates an expected call of DeviceConfirm.
func (mr *MockAuthServiceMockRecorder) DeviceConfirm(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceConfirm", reflect.TypeOf((*MockAuthService)(nil).DeviceConfirm), ctx, input)
}

// DeviceStart mocks base method.
func (m *MockAuthService) DeviceStart(ctx context.Context) (*authservice.DeviceStartOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceStart", ctx)
	ret0, _ := ret[0].(*authservice.DeviceStartOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceStart indicates an expected call of DeviceStart.
func (mr *MockAuthServiceMockRecorder) DeviceStart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceStart", reflect.TypeOf((*MockAuthService)(nil).DeviceStart), ctx)
}

// DeviceToken mocks base method.
func (m *MockAuthService) DeviceToken(ctx context.Context, input *authservice.DeviceTokenInput) (*authservice.DeviceTokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceToken", ctx, input)
	ret0, _ := ret[0].(*authservice.DeviceTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceToken indicates an expected call of DeviceToken.
func (mr *MockAuthServiceMockRecorder) DeviceToken(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceToken", reflect.TypeOf((*MockAuthService)(nil).DeviceToken), ctx, input)
}

// ForgotPassword mocks base method.
func (m *MockAuthService) ForgotPassword(ctx context.Context, input *authservice.ForgotPasswordInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockAuthServiceMockRecorder) ForgotPassword(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockAuthService)(nil).ForgotPassword), ctx, input)
}

// ForgotPasswordCodeResend mocks base method.
func (m *MockAuthService) ForgotPasswordCodeResend(ctx context.Context, input *authservice.ResendCodeInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPasswordCodeResend", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForgotPasswordCodeResend indicates an expected call of ForgotPasswordCodeResend.
func (mr *MockAuthServiceMockRecorder) ForgotPasswordCodeResend(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPasswordCodeResend", reflect.TypeOf((*MockAuthService)(nil).ForgotPasswordCodeResend), ctx, input)
}

// ForgotPasswordVerify mocks base method.
func (m *MockAuthService) ForgotPasswordVerify(ctx context.Context, input *authservice.ForgotPasswordVerifyInput) (*authservice.ResetTokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPasswordVerify", ctx, input)
	ret0, _ := ret[0].(*authservice.ResetTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForgotPasswordVerify indicates an expected call of ForgotPasswordVerify.
func (mr *MockAuthServiceMockRecorder) ForgotPasswordVerify(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPasswordVerify", reflect.TypeOf((*MockAuthService)(nil).ForgotPasswordVerify), ctx, input)
}

// GetMe mocks base method.
func (m *MockAuthService) GetMe(ctx context.Context) (*authservice.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", ctx)
	ret0, _ := ret[0].(*authservice.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockAuthServiceMockRecorder) GetMe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockAuthService)(nil).GetMe), ctx)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, input *authservice.LoginInput) (*authservice.TokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, input)
	ret0, _ := ret[0].(*authservice.TokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, input)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx)
}

// Refresh mocks base method.
func (m *MockAuthService) Refresh(ctx context.Context, input *authservice.RefreshInput) (*authservice.TokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, input)
	ret0, _ := ret[0].(*authservice.TokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthServiceMockRecorder) Refresh(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthService)(nil).Refresh), ctx, input)
}

// Register mocks base method.
func (m *MockAuthService) Register(ctx context.Context, input *authservice.RegisterInput) (*authservice.RegisterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, input)
	ret0, _ := ret[0].(*authservice.RegisterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), ctx, input)
}

// RegisterVerify mocks base method.
func (m *MockAuthService) RegisterVerify(ctx context.Context, input *authservice.VerifyCodeInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterVerify", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterVerify indicates an expected call of RegisterVerify.
func (mr *MockAuthServiceMockRecorder) RegisterVerify(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterVerify", reflect.TypeOf((*MockAuthService)(nil).RegisterVerify), ctx, input)
}

// ResendVerificationCode mocks base method.
func (m *MockAuthService) ResendVerificationCode(ctx context.Context, input *authservice.ResendCodeInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerificationCode", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResendVerificationCode indicates an expected call of ResendVerificationCode.
func (mr *MockAuthServiceMockRecorder) ResendVerificationCode(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerificationCode", reflect.TypeOf((*MockAuthService)(nil).ResendVerificationCode), ctx, input)
}

// ResetPassword mocks base method.
func (m *MockAuthService) ResetPassword(ctx context.Context, input *authservice.ResetPasswordInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthServiceMockRecorder) ResetPassword(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthService)(nil).ResetPassword), ctx, input)
}
