// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/ci_report/ci_report.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/ci_report/ci_report.go -destination=internal/services/ci_report/mocks/ci_report_mocks.go -package=mocks -mock_names=reportCache=MockReportCache,reportForwarder=MockReportForwarder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "notifications/internal/models/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReportCache is a mock of reportCache interface.
type MockReportCache struct {
	ctrl     *gomock.Controller
	recorder *MockReportCacheMockRecorder
	isgomock struct{}
}

// MockReportCacheMockRecorder is the mock recorder for MockReportCache.
type MockReportCacheMockRecorder struct {
	mock *MockReportCache
}

// NewMockReportCache creates a new mock instance.
func NewMockReportCache(ctrl *gomock.Controller) *MockReportCache {
	mock := &MockReportCache{ctrl: ctrl}
	mock.recorder = &MockReportCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportCache) EXPECT() *MockReportCacheMockRecorder {
	return m.recorder
}

// GetLatest mocks base method.
func (m *MockReportCache) GetLatest(ctx context.Context, uid string) (*domain.CIReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatest", ctx, uid)
	ret0, _ := ret[0].(*domain.CIReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatest indicates an expected call of GetLatest.
func (mr *MockReportCacheMockRecorder) GetLatest(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatest", reflect.TypeOf((*MockReportCache)(nil).GetLatest), ctx, uid)
}

// Save mocks base method.
func (m *MockReportCache) Save(ctx context.Context, report *domain.CIReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockReportCacheMockRecorder) Save(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockReportCache)(nil).Save), ctx, report)
}

// MockReportForwarder is a mock of reportForwarder interface.
type MockReportForwarder struct {
	ctrl     *gomock.Controller
	recorder *MockReportForwarderMockRecorder
	isgomock struct{}
}

// MockReportForwarderMockRecorder is the mock recorder for MockReportForwarder.
type MockReportForwarderMockRecorder struct {
	mock *MockReportForwarder
}

// NewMockReportForwarder creates a new mock instance.
func NewMockReportForwarder(ctrl *gomock.Controller) *MockReportForwarder {
	mock := &MockReportForwarder{ctrl: ctrl}
	mock.recorder = &MockReportForwarderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportForwarder) EXPECT() *MockReportForwarderMockRecorder {
	return m.recorder
}

// SendAsync mocks base method.
func (m *MockReportForwarder) SendAsync(ctx context.Context, report *domain.CIReport) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendAsync", ctx, report)
}

// SendAsync indicates an expected call of SendAsync.
func (mr *MockReportForwarderMockRecorder) SendAsync(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAsync", reflect.TypeOf((*MockReportForwarder)(nil).SendAsync), ctx, report)
}
