// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/users.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/users.go -destination=internal/services/mocks/users_mocks.go -package=mocks -mock_names=tokenManager=MockTokenManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"
	records "users/internal/models/records"
	gitauthservice "users/internal/services/git_auth"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenManager is a mock of tokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
	isgomock struct{}
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockTokenManager) GenerateAccessToken(userID, sessionID uuid.UUID) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenManagerMockRecorder) GenerateAccessToken(userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenManager)(nil).GenerateAccessToken), userID, sessionID)
}

// GenerateRefreshToken mocks base method.
func (m *MockTokenManager) GenerateRefreshToken() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockTokenManagerMockRecorder) GenerateRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockTokenManager)(nil).GenerateRefreshToken))
}

// ValidateAccessToken mocks base method.
func (m *MockTokenManager) ValidateAccessToken(tokenString string) (uuid.UUID, uuid.UUID, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenString)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenManagerMockRecorder) ValidateAccessToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenManager)(nil).ValidateAccessToken), tokenString)
}

// MockAvatarStorage is a mock of AvatarStorage interface.
type MockAvatarStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarStorageMockRecorder
	isgomock struct{}
}

// MockAvatarStorageMockRecorder is the mock recorder for MockAvatarStorage.
type MockAvatarStorageMockRecorder struct {
	mock *MockAvatarStorage
}

// NewMockAvatarStorage creates a new mock instance.
func NewMockAvatarStorage(ctrl *gomock.Controller) *MockAvatarStorage {
	mock := &MockAvatarStorage{ctrl: ctrl}
	mock.recorder = &MockAvatarStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarStorage) EXPECT() *MockAvatarStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAvatarStorage) Delete(objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarStorageMockRecorder) Delete(objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarStorage)(nil).Delete), objectKey)
}

// Save mocks base method.
func (m *MockAvatarStorage) Save(identityID uuid.UUID, filename string, r io.Reader) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", identityID, filename, r)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Save indicates an expected call of Save.
func (mr *MockAvatarStorageMockRecorder) Save(identityID, filename, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAvatarStorage)(nil).Save), identityID, filename, r)
}

// MockUserProfileRepository is a mock of UserProfileRepository interface.
type MockUserProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockUserProfileRepositoryMockRecorder is the mock recorder for MockUserProfileRepository.
type MockUserProfileRepositoryMockRecorder struct {
	mock *MockUserProfileRepository
}

// NewMockUserProfileRepository creates a new mock instance.
func NewMockUserProfileRepository(ctrl *gomock.Controller) *MockUserProfileRepository {
	mock := &MockUserProfileRepository{ctrl: ctrl}
	mock.recorder = &MockUserProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileRepository) EXPECT() *MockUserProfileRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserProfileRepository) Create(ctx context.Context, profile *records.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserProfileRepositoryMockRecorder) Create(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProfileRepository)(nil).Create), ctx, profile)
}

// Delete mocks base method.
func (m *MockUserProfileRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserProfileRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserProfileRepository)(nil).Delete), ctx, id)
}

// ExistsByDisplayName mocks base method.
func (m *MockUserProfileRepository) ExistsByDisplayName(ctx context.Context, displayName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByDisplayName", ctx, displayName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByDisplayName indicates an expected call of ExistsByDisplayName.
func (mr *MockUserProfileRepositoryMockRecorder) ExistsByDisplayName(ctx, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByDisplayName", reflect.TypeOf((*MockUserProfileRepository)(nil).ExistsByDisplayName), ctx, displayName)
}

// GetByEmail mocks base method.
func (m *MockUserProfileRepository) GetByEmail(ctx context.Context, email string) (*records.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*records.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserProfileRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserProfileRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserProfileRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserProfileRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserProfileRepository)(nil).GetByID), ctx, id)
}

// GetByIdentityID mocks base method.
func (m *MockUserProfileRepository) GetByIdentityID(ctx context.Context, identityID uuid.UUID) (*records.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdentityID", ctx, identityID)
	ret0, _ := ret[0].(*records.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdentityID indicates an expected call of GetByIdentityID.
func (mr *MockUserProfileRepositoryMockRecorder) GetByIdentityID(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdentityID", reflect.TypeOf((*MockUserProfileRepository)(nil).GetByIdentityID), ctx, identityID)
}

// Update mocks base method.
func (m *MockUserProfileRepository) Update(ctx context.Context, profile *records.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProfileRepositoryMockRecorder) Update(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProfileRepository)(nil).Update), ctx, profile)
}

// MockProcessedEventsRepository is a mock of ProcessedEventsRepository interface.
type MockProcessedEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProcessedEventsRepositoryMockRecorder
	isgomock struct{}
}

// MockProcessedEventsRepositoryMockRecorder is the mock recorder for MockProcessedEventsRepository.
type MockProcessedEventsRepositoryMockRecorder struct {
	mock *MockProcessedEventsRepository
}

// NewMockProcessedEventsRepository creates a new mock instance.
func NewMockProcessedEventsRepository(ctrl *gomock.Controller) *MockProcessedEventsRepository {
	mock := &MockProcessedEventsRepository{ctrl: ctrl}
	mock.recorder = &MockProcessedEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessedEventsRepository) EXPECT() *MockProcessedEventsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProcessedEventsRepository) Create(ctx context.Context, event *records.ProcessedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProcessedEventsRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProcessedEventsRepository)(nil).Create), ctx, event)
}

// Delete mocks base method.
func (m *MockProcessedEventsRepository) Delete(ctx context.Context, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProcessedEventsRepositoryMockRecorder) Delete(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProcessedEventsRepository)(nil).Delete), ctx, eventID)
}

// GetByAggregateID mocks base method.
func (m *MockProcessedEventsRepository) GetByAggregateID(ctx context.Context, aggregateID uuid.UUID) ([]records.ProcessedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAggregateID", ctx, aggregateID)
	ret0, _ := ret[0].([]records.ProcessedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAggregateID indicates an expected call of GetByAggregateID.
func (mr *MockProcessedEventsRepositoryMockRecorder) GetByAggregateID(ctx, aggregateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAggregateID", reflect.TypeOf((*MockProcessedEventsRepository)(nil).GetByAggregateID), ctx, aggregateID)
}

// GetByEventID mocks base method.
func (m *MockProcessedEventsRepository) GetByEventID(ctx context.Context, eventID string) (*records.ProcessedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventID", ctx, eventID)
	ret0, _ := ret[0].(*records.ProcessedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventID indicates an expected call of GetByEventID.
func (mr *MockProcessedEventsRepositoryMockRecorder) GetByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventID", reflect.TypeOf((*MockProcessedEventsRepository)(nil).GetByEventID), ctx, eventID)
}

// Update mocks base method.
func (m *MockProcessedEventsRepository) Update(ctx context.Context, event *records.ProcessedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProcessedEventsRepositoryMockRecorder) Update(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProcessedEventsRepository)(nil).Update), ctx, event)
}

// MockGitAuthService is a mock of GitAuthService interface.
type MockGitAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockGitAuthServiceMockRecorder
	isgomock struct{}
}

// MockGitAuthServiceMockRecorder is the mock recorder for MockGitAuthService.
type MockGitAuthServiceMockRecorder struct {
	mock *MockGitAuthService
}

// NewMockGitAuthService creates a new mock instance.
func NewMockGitAuthService(ctrl *gomock.Controller) *MockGitAuthService {
	mock := &MockGitAuthService{ctrl: ctrl}
	mock.recorder = &MockGitAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitAuthService) EXPECT() *MockGitAuthServiceMockRecorder {
	return m.recorder
}

// GetGitMe mocks base method.
func (m *MockGitAuthService) GetGitMe(ctx context.Context, identityID uuid.UUID) (*gitauthservice.GitMeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitMe", ctx, identityID)
	ret0, _ := ret[0].(*gitauthservice.GitMeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitMe indicates an expected call of GetGitMe.
func (mr *MockGitAuthServiceMockRecorder) GetGitMe(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitMe", reflect.TypeOf((*MockGitAuthService)(nil).GetGitMe), ctx, identityID)
}

// RegisterGitUser mocks base method.
func (m *MockGitAuthService) RegisterGitUser(ctx context.Context, input *gitauthservice.RegisterGitUserInput) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterGitUser", ctx, input)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterGitUser indicates an expected call of RegisterGitUser.
func (mr *MockGitAuthServiceMockRecorder) RegisterGitUser(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterGitUser", reflect.TypeOf((*MockGitAuthService)(nil).RegisterGitUser), ctx, input)
}
