// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers/reports/reports_handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/http/handlers/reports/reports_handlers.go -destination=internal/http/handlers/reports/mocks/reports_handler_mocks.go -package=mocks -mock_names=reportsService=MockReportsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	reportsservice "tasks/internal/services/reports"

	gomock "go.uber.org/mock/gomock"
)

// MockReportsService is a mock of reportsService interface.
type MockReportsService struct {
	ctrl     *gomock.Controller
	recorder *MockReportsServiceMockRecorder
	isgomock struct{}
}

// MockReportsServiceMockRecorder is the mock recorder for MockReportsService.
type MockReportsServiceMockRecorder struct {
	mock *MockReportsService
}

// NewMockReportsService creates a new mock instance.
func NewMockReportsService(ctrl *gomock.Controller) *MockReportsService {
	mock := &MockReportsService{ctrl: ctrl}
	mock.recorder = &MockReportsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportsService) EXPECT() *MockReportsServiceMockRecorder {
	return m.recorder
}

// CreateReport mocks base method.
func (m *MockReportsService) CreateReport(ctx context.Context, in *reportsservice.CreateReportInput) (*reportsservice.ReportOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReport", ctx, in)
	ret0, _ := ret[0].(*reportsservice.ReportOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockReportsServiceMockRecorder) CreateReport(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockReportsService)(nil).CreateReport), ctx, in)
}

// GetReport mocks base method.
func (m *MockReportsService) GetReport(ctx context.Context, in *reportsservice.GetInput) (*reportsservice.ReportOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReport", ctx, in)
	ret0, _ := ret[0].(*reportsservice.ReportOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReport indicates an expected call of GetReport.
func (mr *MockReportsServiceMockRecorder) GetReport(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReport", reflect.TypeOf((*MockReportsService)(nil).GetReport), ctx, in)
}

// ListReports mocks base method.
func (m *MockReportsService) ListReports(ctx context.Context, in *reportsservice.ListInput) (*reportsservice.ListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReports", ctx, in)
	ret0, _ := ret[0].(*reportsservice.ListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReports indicates an expected call of ListReports.
func (mr *MockReportsServiceMockRecorder) ListReports(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReports", reflect.TypeOf((*MockReportsService)(nil).ListReports), ctx, in)
}
