// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/git_tasks/git_tasks.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/git_tasks/git_tasks.go -destination=internal/services/git_tasks/mocks/git_tasks_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	records "tasks/internal/models/records"
	clientsdto "tasks/pkg/http_clients/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// GetByTaskName mocks base method.
func (m *MockTaskRepository) GetByTaskName(ctx context.Context, taskName string) (*records.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTaskName", ctx, taskName)
	ret0, _ := ret[0].(*records.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTaskName indicates an expected call of GetByTaskName.
func (mr *MockTaskRepositoryMockRecorder) GetByTaskName(ctx, taskName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTaskName", reflect.TypeOf((*MockTaskRepository)(nil).GetByTaskName), ctx, taskName)
}

// MockPulledTaskRepository is a mock of PulledTaskRepository interface.
type MockPulledTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPulledTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockPulledTaskRepositoryMockRecorder is the mock recorder for MockPulledTaskRepository.
type MockPulledTaskRepositoryMockRecorder struct {
	mock *MockPulledTaskRepository
}

// NewMockPulledTaskRepository creates a new mock instance.
func NewMockPulledTaskRepository(ctrl *gomock.Controller) *MockPulledTaskRepository {
	mock := &MockPulledTaskRepository{ctrl: ctrl}
	mock.recorder = &MockPulledTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPulledTaskRepository) EXPECT() *MockPulledTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPulledTaskRepository) Create(ctx context.Context, task *records.PulledTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPulledTaskRepositoryMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPulledTaskRepository)(nil).Create), ctx, task)
}

// GetByTaskIDAndIdentityID mocks base method.
func (m *MockPulledTaskRepository) GetByTaskIDAndIdentityID(ctx context.Context, taskID, identityID uuid.UUID) (*records.PulledTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTaskIDAndIdentityID", ctx, taskID, identityID)
	ret0, _ := ret[0].(*records.PulledTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTaskIDAndIdentityID indicates an expected call of GetByTaskIDAndIdentityID.
func (mr *MockPulledTaskRepositoryMockRecorder) GetByTaskIDAndIdentityID(ctx, taskID, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTaskIDAndIdentityID", reflect.TypeOf((*MockPulledTaskRepository)(nil).GetByTaskIDAndIdentityID), ctx, taskID, identityID)
}

// MockUsersClient is a mock of UsersClient interface.
type MockUsersClient struct {
	ctrl     *gomock.Controller
	recorder *MockUsersClientMockRecorder
	isgomock struct{}
}

// MockUsersClientMockRecorder is the mock recorder for MockUsersClient.
type MockUsersClientMockRecorder struct {
	mock *MockUsersClient
}

// NewMockUsersClient creates a new mock instance.
func NewMockUsersClient(ctrl *gomock.Controller) *MockUsersClient {
	mock := &MockUsersClient{ctrl: ctrl}
	mock.recorder = &MockUsersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersClient) EXPECT() *MockUsersClientMockRecorder {
	return m.recorder
}

// GetGitUser mocks base method.
func (m *MockUsersClient) GetGitUser(ctx context.Context, req *clientsdto.GitUserRequest) (*clientsdto.GitUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitUser", ctx, req)
	ret0, _ := ret[0].(*clientsdto.GitUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitUser indicates an expected call of GetGitUser.
func (mr *MockUsersClientMockRecorder) GetGitUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitUser", reflect.TypeOf((*MockUsersClient)(nil).GetGitUser), ctx, req)
}

// MockGitTasksClient is a mock of GitTasksClient interface.
type MockGitTasksClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitTasksClientMockRecorder
	isgomock struct{}
}

// MockGitTasksClientMockRecorder is the mock recorder for MockGitTasksClient.
type MockGitTasksClientMockRecorder struct {
	mock *MockGitTasksClient
}

// NewMockGitTasksClient creates a new mock instance.
func NewMockGitTasksClient(ctrl *gomock.Controller) *MockGitTasksClient {
	mock := &MockGitTasksClient{ctrl: ctrl}
	mock.recorder = &MockGitTasksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitTasksClient) EXPECT() *MockGitTasksClientMockRecorder {
	return m.recorder
}

// GitTaskCreate mocks base method.
func (m *MockGitTasksClient) GitTaskCreate(ctx context.Context, req *clientsdto.GitTaskCreateRequest) (*clientsdto.GitTaskCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitTaskCreate", ctx, req)
	ret0, _ := ret[0].(*clientsdto.GitTaskCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitTaskCreate indicates an expected call of GitTaskCreate.
func (mr *MockGitTasksClientMockRecorder) GitTaskCreate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitTaskCreate", reflect.TypeOf((*MockGitTasksClient)(nil).GitTaskCreate), ctx, req)
}
