// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers/git_tasks/git_tasks_handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/http/handlers/git_tasks/git_tasks_handlers.go -destination=internal/http/handlers/git_tasks/mocks/git_tasks_handler_mocks.go -package=mocks -mock_names=gitTasksService=MockGitTasksService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	gittasksservice "tasks/internal/services/git_tasks"

	gomock "go.uber.org/mock/gomock"
)

// MockGitTasksService is a mock of gitTasksService interface.
type MockGitTasksService struct {
	ctrl     *gomock.Controller
	recorder *MockGitTasksServiceMockRecorder
	isgomock struct{}
}

// MockGitTasksServiceMockRecorder is the mock recorder for MockGitTasksService.
type MockGitTasksServiceMockRecorder struct {
	mock *MockGitTasksService
}

// NewMockGitTasksService creates a new mock instance.
func NewMockGitTasksService(ctrl *gomock.Controller) *MockGitTasksService {
	mock := &MockGitTasksService{ctrl: ctrl}
	mock.recorder = &MockGitTasksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitTasksService) EXPECT() *MockGitTasksServiceMockRecorder {
	return m.recorder
}

// CreateGitTask mocks base method.
func (m *MockGitTasksService) CreateGitTask(ctx context.Context, input *gittasksservice.GitTaskCreateInput) (*gittasksservice.GitTaskCreateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGitTask", ctx, input)
	ret0, _ := ret[0].(*gittasksservice.GitTaskCreateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGitTask indicates an expected call of CreateGitTask.
func (mr *MockGitTasksServiceMockRecorder) CreateGitTask(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGitTask", reflect.TypeOf((*MockGitTasksService)(nil).CreateGitTask), ctx, input)
}
