// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/tasks.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/tasks.go -destination=internal/services/mocks/services_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	records "tasks/internal/models/records"
	services "tasks/internal/services"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaskRepository) Create(ctx context.Context, task *records.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepository)(nil).Create), ctx, task)
}

// Delete mocks base method.
func (m *MockTaskRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTaskRepository) GetByID(ctx context.Context, id uuid.UUID) (*records.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*records.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepository)(nil).GetByID), ctx, id)
}

// GetLanguagesByIDs mocks base method.
func (m *MockTaskRepository) GetLanguagesByIDs(ctx context.Context, ids []uuid.UUID) ([]records.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguagesByIDs", ctx, ids)
	ret0, _ := ret[0].([]records.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLanguagesByIDs indicates an expected call of GetLanguagesByIDs.
func (mr *MockTaskRepositoryMockRecorder) GetLanguagesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguagesByIDs", reflect.TypeOf((*MockTaskRepository)(nil).GetLanguagesByIDs), ctx, ids)
}

// GetLanguagesByTaskID mocks base method.
func (m *MockTaskRepository) GetLanguagesByTaskID(ctx context.Context, taskID uuid.UUID) ([]records.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguagesByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]records.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLanguagesByTaskID indicates an expected call of GetLanguagesByTaskID.
func (mr *MockTaskRepositoryMockRecorder) GetLanguagesByTaskID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguagesByTaskID", reflect.TypeOf((*MockTaskRepository)(nil).GetLanguagesByTaskID), ctx, taskID)
}

// GetTagsByIDs mocks base method.
func (m *MockTaskRepository) GetTagsByIDs(ctx context.Context, ids []uuid.UUID) ([]records.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByIDs", ctx, ids)
	ret0, _ := ret[0].([]records.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByIDs indicates an expected call of GetTagsByIDs.
func (mr *MockTaskRepositoryMockRecorder) GetTagsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByIDs", reflect.TypeOf((*MockTaskRepository)(nil).GetTagsByIDs), ctx, ids)
}

// GetTagsByTaskID mocks base method.
func (m *MockTaskRepository) GetTagsByTaskID(ctx context.Context, taskID uuid.UUID) ([]records.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]records.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByTaskID indicates an expected call of GetTagsByTaskID.
func (mr *MockTaskRepositoryMockRecorder) GetTagsByTaskID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByTaskID", reflect.TypeOf((*MockTaskRepository)(nil).GetTagsByTaskID), ctx, taskID)
}

// List mocks base method.
func (m *MockTaskRepository) List(ctx context.Context, limit int32, cursor *string, filters services.ListFilters) ([]records.TaskListItem, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, cursor, filters)
	ret0, _ := ret[0].([]records.TaskListItem)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepositoryMockRecorder) List(ctx, limit, cursor, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepository)(nil).List), ctx, limit, cursor, filters)
}

// ListLanguages mocks base method.
func (m *MockTaskRepository) ListLanguages(ctx context.Context) ([]records.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx)
	ret0, _ := ret[0].([]records.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockTaskRepositoryMockRecorder) ListLanguages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockTaskRepository)(nil).ListLanguages), ctx)
}

// ListTags mocks base method.
func (m *MockTaskRepository) ListTags(ctx context.Context) ([]records.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx)
	ret0, _ := ret[0].([]records.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockTaskRepositoryMockRecorder) ListTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockTaskRepository)(nil).ListTags), ctx)
}

// SetLanguages mocks base method.
func (m *MockTaskRepository) SetLanguages(ctx context.Context, taskID uuid.UUID, languageIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLanguages", ctx, taskID, languageIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLanguages indicates an expected call of SetLanguages.
func (mr *MockTaskRepositoryMockRecorder) SetLanguages(ctx, taskID, languageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLanguages", reflect.TypeOf((*MockTaskRepository)(nil).SetLanguages), ctx, taskID, languageIDs)
}

// SetTags mocks base method.
func (m *MockTaskRepository) SetTags(ctx context.Context, taskID uuid.UUID, tagIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTags", ctx, taskID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTags indicates an expected call of SetTags.
func (mr *MockTaskRepositoryMockRecorder) SetTags(ctx, taskID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTags", reflect.TypeOf((*MockTaskRepository)(nil).SetTags), ctx, taskID, tagIDs)
}

// Update mocks base method.
func (m *MockTaskRepository) Update(ctx context.Context, task *records.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepositoryMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepository)(nil).Update), ctx, task)
}
