// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/reports/reports.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/reports/reports.go -destination=internal/services/reports/mocks/reports_mocks.go -package=mocks -mock_names=reportRepository=MockReportRepository,taskRepository=MockTaskRepository,usersClient=MockUsersClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	records "tasks/internal/models/records"
	clientsdto "tasks/pkg/http_clients/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReportRepository is a mock of reportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// GetByIDAndUsername mocks base method.
func (m *MockReportRepository) GetByIDAndUsername(ctx context.Context, id uuid.UUID, username string) (*records.CIReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndUsername", ctx, id, username)
	ret0, _ := ret[0].(*records.CIReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndUsername indicates an expected call of GetByIDAndUsername.
func (mr *MockReportRepositoryMockRecorder) GetByIDAndUsername(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndUsername", reflect.TypeOf((*MockReportRepository)(nil).GetByIDAndUsername), ctx, id, username)
}

// ListByUsername mocks base method.
func (m *MockReportRepository) ListByUsername(ctx context.Context, username string, status *string, limit int32, cursor *string) ([]records.CIReport, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUsername", ctx, username, status, limit, cursor)
	ret0, _ := ret[0].([]records.CIReport)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUsername indicates an expected call of ListByUsername.
func (mr *MockReportRepositoryMockRecorder) ListByUsername(ctx, username, status, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUsername", reflect.TypeOf((*MockReportRepository)(nil).ListByUsername), ctx, username, status, limit, cursor)
}

// ListByUsernameAndTask mocks base method.
func (m *MockReportRepository) ListByUsernameAndTask(ctx context.Context, username, taskName string, status *string, limit int32, cursor *string) ([]records.CIReport, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUsernameAndTask", ctx, username, taskName, status, limit, cursor)
	ret0, _ := ret[0].([]records.CIReport)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUsernameAndTask indicates an expected call of ListByUsernameAndTask.
func (mr *MockReportRepositoryMockRecorder) ListByUsernameAndTask(ctx, username, taskName, status, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUsernameAndTask", reflect.TypeOf((*MockReportRepository)(nil).ListByUsernameAndTask), ctx, username, taskName, status, limit, cursor)
}

// Upsert mocks base method.
func (m *MockReportRepository) Upsert(ctx context.Context, rep *records.CIReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, rep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockReportRepositoryMockRecorder) Upsert(ctx, rep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockReportRepository)(nil).Upsert), ctx, rep)
}

// MockTaskRepository is a mock of taskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// GetByTaskName mocks base method.
func (m *MockTaskRepository) GetByTaskName(ctx context.Context, taskName string) (*records.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTaskName", ctx, taskName)
	ret0, _ := ret[0].(*records.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTaskName indicates an expected call of GetByTaskName.
func (mr *MockTaskRepositoryMockRecorder) GetByTaskName(ctx, taskName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTaskName", reflect.TypeOf((*MockTaskRepository)(nil).GetByTaskName), ctx, taskName)
}

// MockUsersClient is a mock of usersClient interface.
type MockUsersClient struct {
	ctrl     *gomock.Controller
	recorder *MockUsersClientMockRecorder
	isgomock struct{}
}

// MockUsersClientMockRecorder is the mock recorder for MockUsersClient.
type MockUsersClientMockRecorder struct {
	mock *MockUsersClient
}

// NewMockUsersClient creates a new mock instance.
func NewMockUsersClient(ctrl *gomock.Controller) *MockUsersClient {
	mock := &MockUsersClient{ctrl: ctrl}
	mock.recorder = &MockUsersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersClient) EXPECT() *MockUsersClientMockRecorder {
	return m.recorder
}

// GetGitUser mocks base method.
func (m *MockUsersClient) GetGitUser(ctx context.Context, req *clientsdto.GitUserRequest) (*clientsdto.GitUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitUser", ctx, req)
	ret0, _ := ret[0].(*clientsdto.GitUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitUser indicates an expected call of GetGitUser.
func (mr *MockUsersClientMockRecorder) GetGitUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitUser", reflect.TypeOf((*MockUsersClient)(nil).GetGitUser), ctx, req)
}
