// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/report/report.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/report/report.go -destination=internal/services/report/mocks/report_mocks.go -package=mocks -mock_names=reportSender=MockReportSender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	clientsdto "notifications/pkg/http_clients/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReportSender is a mock of reportSender interface.
type MockReportSender struct {
	ctrl     *gomock.Controller
	recorder *MockReportSenderMockRecorder
	isgomock struct{}
}

// MockReportSenderMockRecorder is the mock recorder for MockReportSender.
type MockReportSenderMockRecorder struct {
	mock *MockReportSender
}

// NewMockReportSender creates a new mock instance.
func NewMockReportSender(ctrl *gomock.Controller) *MockReportSender {
	mock := &MockReportSender{ctrl: ctrl}
	mock.recorder = &MockReportSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportSender) EXPECT() *MockReportSenderMockRecorder {
	return m.recorder
}

// SendReport mocks base method.
func (m *MockReportSender) SendReport(ctx context.Context, req *clientsdto.CreateReportRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReport", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReport indicates an expected call of SendReport.
func (mr *MockReportSenderMockRecorder) SendReport(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReport", reflect.TypeOf((*MockReportSender)(nil).SendReport), ctx, req)
}
